//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.EmpleadoServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityEmpleado", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion))]
    public partial class EntityEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApellidosField;
        
        private string CodTiendaField;
        
        private string DNIField;
        
        private int EstadoField;
        
        private char EstadoCivilField;
        
        private System.DateTime FechaNacimientoField;
        
        private int IdCargoField;
        
        private SGI.Proxy.Services.EmpleadoServices.KeyEmpleado KeyField;
        
        private string NombresField;
        
        private char SexoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellidos
        {
            get
            {
                return this.ApellidosField;
            }
            set
            {
                this.ApellidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTienda
        {
            get
            {
                return this.CodTiendaField;
            }
            set
            {
                this.CodTiendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI
        {
            get
            {
                return this.DNIField;
            }
            set
            {
                this.DNIField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char EstadoCivil
        {
            get
            {
                return this.EstadoCivilField;
            }
            set
            {
                this.EstadoCivilField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento
        {
            get
            {
                return this.FechaNacimientoField;
            }
            set
            {
                this.FechaNacimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCargo
        {
            get
            {
                return this.IdCargoField;
            }
            set
            {
                this.IdCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.EmpleadoServices.KeyEmpleado Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombres
        {
            get
            {
                return this.NombresField;
            }
            set
            {
                this.NombresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Sexo
        {
            get
            {
                return this.SexoField;
            }
            set
            {
                this.SexoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyEmpleado", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyEmpleado : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDEmpleadoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpleado
        {
            get
            {
                return this.IDEmpleadoField;
            }
            set
            {
                this.IDEmpleadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityEmpleadoPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityEmpleadoPaginacion : SGI.Proxy.Services.EmpleadoServices.EntityEmpleado
    {
        
        private SGI.Proxy.Services.EmpleadoServices.EntityPaginacion EntityPaginacionField;
        
        private string EstadoCivilNombreField;
        
        private string EstadoNombreField;
        
        private string NombreCargoField;
        
        private string NombreTiendaField;
        
        private string SexoNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.EmpleadoServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCivilNombre
        {
            get
            {
                return this.EstadoCivilNombreField;
            }
            set
            {
                this.EstadoCivilNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoNombre
        {
            get
            {
                return this.EstadoNombreField;
            }
            set
            {
                this.EstadoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCargo
        {
            get
            {
                return this.NombreCargoField;
            }
            set
            {
                this.NombreCargoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTienda
        {
            get
            {
                return this.NombreTiendaField;
            }
            set
            {
                this.NombreTiendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SexoNombre
        {
            get
            {
                return this.SexoNombreField;
            }
            set
            {
                this.SexoNombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.EmpleadoServices.IEmpleadoServices")]
    public interface IEmpleadoServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/SelectTest", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectTestResponse")]
        SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[] SelectTest();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/SelectTest", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectTestResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[]> SelectTestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/SelectByKey", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectByKeyResponse")]
        SGI.Proxy.Services.EmpleadoServices.EntityEmpleado SelectByKey(SGI.Proxy.Services.EmpleadoServices.KeyEmpleado oKeyEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/SelectByKey", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> SelectByKeyAsync(SGI.Proxy.Services.EmpleadoServices.KeyEmpleado oKeyEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Select", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectResponse")]
        SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[] Select(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Select", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[]> SelectAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/SelectPagging", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectPaggingResponse")]
        SGI.Proxy.Services.EmpleadoServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.EmpleadoServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/SelectPagging", ReplyAction="http://tempuri.org/IEmpleadoServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.EmpleadoServices.SelectPaggingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Insert", ReplyAction="http://tempuri.org/IEmpleadoServices/InsertResponse")]
        SGI.Proxy.Services.EmpleadoServices.EntityEmpleado Insert(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Insert", ReplyAction="http://tempuri.org/IEmpleadoServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> InsertAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Update", ReplyAction="http://tempuri.org/IEmpleadoServices/UpdateResponse")]
        SGI.Proxy.Services.EmpleadoServices.EntityEmpleado Update(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Update", ReplyAction="http://tempuri.org/IEmpleadoServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> UpdateAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Delete", ReplyAction="http://tempuri.org/IEmpleadoServices/DeleteResponse")]
        SGI.Proxy.Services.EmpleadoServices.EntityEmpleado Delete(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpleadoServices/Delete", ReplyAction="http://tempuri.org/IEmpleadoServices/DeleteResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> DeleteAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion oEntityEmpleadoPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion oEntityEmpleadoPaginacion)
        {
            this.oEntityEmpleadoPaginacion = oEntityEmpleadoPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion oEntityEmpleadoPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion[] SelectPaggingResult, SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion oEntityEmpleadoPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityEmpleadoPaginacion = oEntityEmpleadoPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpleadoServicesChannel : SGI.Proxy.Services.EmpleadoServices.IEmpleadoServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpleadoServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.EmpleadoServices.IEmpleadoServices>, SGI.Proxy.Services.EmpleadoServices.IEmpleadoServices
    {
        
        public EmpleadoServicesClient()
        {
        }
        
        public EmpleadoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public EmpleadoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public EmpleadoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public EmpleadoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[] SelectTest()
        {
            return base.Channel.SelectTest();
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[]> SelectTestAsync()
        {
            return base.Channel.SelectTestAsync();
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleado SelectByKey(SGI.Proxy.Services.EmpleadoServices.KeyEmpleado oKeyEmpleado)
        {
            return base.Channel.SelectByKey(oKeyEmpleado);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> SelectByKeyAsync(SGI.Proxy.Services.EmpleadoServices.KeyEmpleado oKeyEmpleado)
        {
            return base.Channel.SelectByKeyAsync(oKeyEmpleado);
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[] Select(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.Select(oEntityEmpleado);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado[]> SelectAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.SelectAsync(oEntityEmpleado);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.EmpleadoServices.SelectPaggingResponse SGI.Proxy.Services.EmpleadoServices.IEmpleadoServices.SelectPagging(SGI.Proxy.Services.EmpleadoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion[] SelectPagging(ref SGI.Proxy.Services.EmpleadoServices.EntityEmpleadoPaginacion oEntityEmpleadoPaginacion)
        {
            SGI.Proxy.Services.EmpleadoServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.EmpleadoServices.SelectPaggingRequest();
            inValue.oEntityEmpleadoPaginacion = oEntityEmpleadoPaginacion;
            SGI.Proxy.Services.EmpleadoServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.EmpleadoServices.IEmpleadoServices)(this)).SelectPagging(inValue);
            oEntityEmpleadoPaginacion = retVal.oEntityEmpleadoPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.EmpleadoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleado Insert(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.Insert(oEntityEmpleado);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> InsertAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.InsertAsync(oEntityEmpleado);
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleado Update(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.Update(oEntityEmpleado);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> UpdateAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.UpdateAsync(oEntityEmpleado);
        }
        
        public SGI.Proxy.Services.EmpleadoServices.EntityEmpleado Delete(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.Delete(oEntityEmpleado);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.EmpleadoServices.EntityEmpleado> DeleteAsync(SGI.Proxy.Services.EmpleadoServices.EntityEmpleado oEntityEmpleado)
        {
            return base.Channel.DeleteAsync(oEntityEmpleado);
        }
    }
}
