//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.GrupoServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyGrupo", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyGrupo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDGrupoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrupo
        {
            get
            {
                return this.IDGrupoField;
            }
            set
            {
                this.IDGrupoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityGrupo", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion))]
    public partial class EntityGrupo : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DescripcionCortaField;
        
        private string DescripcionLargaField;
        
        private int EstadoField;
        
        private int IDGrupoPadreField;
        
        private SGI.Proxy.Services.GrupoServices.KeyGrupo KeyField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCorta
        {
            get
            {
                return this.DescripcionCortaField;
            }
            set
            {
                this.DescripcionCortaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLarga
        {
            get
            {
                return this.DescripcionLargaField;
            }
            set
            {
                this.DescripcionLargaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDGrupoPadre
        {
            get
            {
                return this.IDGrupoPadreField;
            }
            set
            {
                this.IDGrupoPadreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.GrupoServices.KeyGrupo Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityGrupoPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Pagination")]
    public partial class EntityGrupoPaginacion : SGI.Proxy.Services.GrupoServices.EntityGrupo
    {
        
        private SGI.Proxy.Services.GrupoServices.EntityPaginacion EntityPaginacionField;
        
        private string EstadoNombreField;
        
        private string GrupoPadreNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.GrupoServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoNombre
        {
            get
            {
                return this.EstadoNombreField;
            }
            set
            {
                this.EstadoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoPadreNombre
        {
            get
            {
                return this.GrupoPadreNombreField;
            }
            set
            {
                this.GrupoPadreNombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.GrupoServices.IGrupoServices")]
    public interface IGrupoServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/SelectByKey", ReplyAction="http://tempuri.org/IGrupoServices/SelectByKeyResponse")]
        SGI.Proxy.Services.GrupoServices.EntityGrupo SelectByKey(SGI.Proxy.Services.GrupoServices.KeyGrupo oKeyGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/SelectByKey", ReplyAction="http://tempuri.org/IGrupoServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> SelectByKeyAsync(SGI.Proxy.Services.GrupoServices.KeyGrupo oKeyGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Select", ReplyAction="http://tempuri.org/IGrupoServices/SelectResponse")]
        SGI.Proxy.Services.GrupoServices.EntityGrupo[] Select(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Select", ReplyAction="http://tempuri.org/IGrupoServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo[]> SelectAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/SelectPagging", ReplyAction="http://tempuri.org/IGrupoServices/SelectPaggingResponse")]
        SGI.Proxy.Services.GrupoServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.GrupoServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/SelectPagging", ReplyAction="http://tempuri.org/IGrupoServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.GrupoServices.SelectPaggingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Insert", ReplyAction="http://tempuri.org/IGrupoServices/InsertResponse")]
        SGI.Proxy.Services.GrupoServices.EntityGrupo Insert(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Insert", ReplyAction="http://tempuri.org/IGrupoServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> InsertAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Update", ReplyAction="http://tempuri.org/IGrupoServices/UpdateResponse")]
        SGI.Proxy.Services.GrupoServices.EntityGrupo Update(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Update", ReplyAction="http://tempuri.org/IGrupoServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> UpdateAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Delete", ReplyAction="http://tempuri.org/IGrupoServices/DeleteResponse")]
        SGI.Proxy.Services.GrupoServices.EntityGrupo Delete(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGrupoServices/Delete", ReplyAction="http://tempuri.org/IGrupoServices/DeleteResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> DeleteAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion oEntityGrupoPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion oEntityGrupoPaginacion)
        {
            this.oEntityGrupoPaginacion = oEntityGrupoPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion oEntityGrupoPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion[] SelectPaggingResult, SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion oEntityGrupoPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityGrupoPaginacion = oEntityGrupoPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGrupoServicesChannel : SGI.Proxy.Services.GrupoServices.IGrupoServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GrupoServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.GrupoServices.IGrupoServices>, SGI.Proxy.Services.GrupoServices.IGrupoServices
    {
        
        public GrupoServicesClient()
        {
        }
        
        public GrupoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public GrupoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GrupoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public GrupoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.GrupoServices.EntityGrupo SelectByKey(SGI.Proxy.Services.GrupoServices.KeyGrupo oKeyGrupo)
        {
            return base.Channel.SelectByKey(oKeyGrupo);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> SelectByKeyAsync(SGI.Proxy.Services.GrupoServices.KeyGrupo oKeyGrupo)
        {
            return base.Channel.SelectByKeyAsync(oKeyGrupo);
        }
        
        public SGI.Proxy.Services.GrupoServices.EntityGrupo[] Select(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.Select(oEntityGrupo);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo[]> SelectAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.SelectAsync(oEntityGrupo);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.GrupoServices.SelectPaggingResponse SGI.Proxy.Services.GrupoServices.IGrupoServices.SelectPagging(SGI.Proxy.Services.GrupoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion[] SelectPagging(ref SGI.Proxy.Services.GrupoServices.EntityGrupoPaginacion oEntityGrupoPaginacion)
        {
            SGI.Proxy.Services.GrupoServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.GrupoServices.SelectPaggingRequest();
            inValue.oEntityGrupoPaginacion = oEntityGrupoPaginacion;
            SGI.Proxy.Services.GrupoServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.GrupoServices.IGrupoServices)(this)).SelectPagging(inValue);
            oEntityGrupoPaginacion = retVal.oEntityGrupoPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.GrupoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
        
        public SGI.Proxy.Services.GrupoServices.EntityGrupo Insert(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.Insert(oEntityGrupo);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> InsertAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.InsertAsync(oEntityGrupo);
        }
        
        public SGI.Proxy.Services.GrupoServices.EntityGrupo Update(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.Update(oEntityGrupo);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> UpdateAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.UpdateAsync(oEntityGrupo);
        }
        
        public SGI.Proxy.Services.GrupoServices.EntityGrupo Delete(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.Delete(oEntityGrupo);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.GrupoServices.EntityGrupo> DeleteAsync(SGI.Proxy.Services.GrupoServices.EntityGrupo oEntityGrupo)
        {
            return base.Channel.DeleteAsync(oEntityGrupo);
        }
    }
}
