//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.DetallePedidoServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyDetallePedido", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyDetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDPedidoField;
        
        private int IDProductoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPedido
        {
            get
            {
                return this.IDPedidoField;
            }
            set
            {
                this.IDPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProducto
        {
            get
            {
                return this.IDProductoField;
            }
            set
            {
                this.IDProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityDetallePedido", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion))]
    public partial class EntityDetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CantidadField;
        
        private int EstadoField;
        
        private SGI.Proxy.Services.DetallePedidoServices.KeyDetallePedido KeyField;
        
        private decimal RetencionField;
        
        private decimal TotalBrutoField;
        
        private decimal TotalNetoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.DetallePedidoServices.KeyDetallePedido Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Retencion
        {
            get
            {
                return this.RetencionField;
            }
            set
            {
                this.RetencionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBruto
        {
            get
            {
                return this.TotalBrutoField;
            }
            set
            {
                this.TotalBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalNeto
        {
            get
            {
                return this.TotalNetoField;
            }
            set
            {
                this.TotalNetoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityDetallePedidoPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Pagination")]
    public partial class EntityDetallePedidoPaginacion : SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido
    {
        
        private SGI.Proxy.Services.DetallePedidoServices.EntityPaginacion EntityPaginacionField;
        
        private string EstadoNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.DetallePedidoServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoNombre
        {
            get
            {
                return this.EstadoNombreField;
            }
            set
            {
                this.EstadoNombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.DetallePedidoServices.IDetallePedidoServices")]
    public interface IDetallePedidoServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/SelectByKey", ReplyAction="http://tempuri.org/IDetallePedidoServices/SelectByKeyResponse")]
        SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido SelectByKey(SGI.Proxy.Services.DetallePedidoServices.KeyDetallePedido oKeyDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/SelectByKey", ReplyAction="http://tempuri.org/IDetallePedidoServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> SelectByKeyAsync(SGI.Proxy.Services.DetallePedidoServices.KeyDetallePedido oKeyDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Select", ReplyAction="http://tempuri.org/IDetallePedidoServices/SelectResponse")]
        SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido[] Select(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Select", ReplyAction="http://tempuri.org/IDetallePedidoServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido[]> SelectAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/SelectPagging", ReplyAction="http://tempuri.org/IDetallePedidoServices/SelectPaggingResponse")]
        SGI.Proxy.Services.DetallePedidoServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.DetallePedidoServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/SelectPagging", ReplyAction="http://tempuri.org/IDetallePedidoServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.DetallePedidoServices.SelectPaggingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Insert", ReplyAction="http://tempuri.org/IDetallePedidoServices/InsertResponse")]
        SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido Insert(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Insert", ReplyAction="http://tempuri.org/IDetallePedidoServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> InsertAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Update", ReplyAction="http://tempuri.org/IDetallePedidoServices/UpdateResponse")]
        SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido Update(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Update", ReplyAction="http://tempuri.org/IDetallePedidoServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> UpdateAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Delete", ReplyAction="http://tempuri.org/IDetallePedidoServices/DeleteResponse")]
        SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido Delete(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDetallePedidoServices/Delete", ReplyAction="http://tempuri.org/IDetallePedidoServices/DeleteResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> DeleteAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion oEntityDetallePedidoPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion oEntityDetallePedidoPaginacion)
        {
            this.oEntityDetallePedidoPaginacion = oEntityDetallePedidoPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion oEntityDetallePedidoPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion[] SelectPaggingResult, SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion oEntityDetallePedidoPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityDetallePedidoPaginacion = oEntityDetallePedidoPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDetallePedidoServicesChannel : SGI.Proxy.Services.DetallePedidoServices.IDetallePedidoServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DetallePedidoServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.DetallePedidoServices.IDetallePedidoServices>, SGI.Proxy.Services.DetallePedidoServices.IDetallePedidoServices
    {
        
        public DetallePedidoServicesClient()
        {
        }
        
        public DetallePedidoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DetallePedidoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DetallePedidoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DetallePedidoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido SelectByKey(SGI.Proxy.Services.DetallePedidoServices.KeyDetallePedido oKeyDetallePedido)
        {
            return base.Channel.SelectByKey(oKeyDetallePedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> SelectByKeyAsync(SGI.Proxy.Services.DetallePedidoServices.KeyDetallePedido oKeyDetallePedido)
        {
            return base.Channel.SelectByKeyAsync(oKeyDetallePedido);
        }
        
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido[] Select(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.Select(oEntityDetallePedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido[]> SelectAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.SelectAsync(oEntityDetallePedido);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.DetallePedidoServices.SelectPaggingResponse SGI.Proxy.Services.DetallePedidoServices.IDetallePedidoServices.SelectPagging(SGI.Proxy.Services.DetallePedidoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion[] SelectPagging(ref SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedidoPaginacion oEntityDetallePedidoPaginacion)
        {
            SGI.Proxy.Services.DetallePedidoServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.DetallePedidoServices.SelectPaggingRequest();
            inValue.oEntityDetallePedidoPaginacion = oEntityDetallePedidoPaginacion;
            SGI.Proxy.Services.DetallePedidoServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.DetallePedidoServices.IDetallePedidoServices)(this)).SelectPagging(inValue);
            oEntityDetallePedidoPaginacion = retVal.oEntityDetallePedidoPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.DetallePedidoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
        
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido Insert(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.Insert(oEntityDetallePedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> InsertAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.InsertAsync(oEntityDetallePedido);
        }
        
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido Update(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.Update(oEntityDetallePedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> UpdateAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.UpdateAsync(oEntityDetallePedido);
        }
        
        public SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido Delete(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.Delete(oEntityDetallePedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido> DeleteAsync(SGI.Proxy.Services.DetallePedidoServices.EntityDetallePedido oEntityDetallePedido)
        {
            return base.Channel.DeleteAsync(oEntityDetallePedido);
        }
    }
}
