//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.PedidoServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyPedido", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyPedido : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDPedidoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPedido
        {
            get
            {
                return this.IDPedidoField;
            }
            set
            {
                this.IDPedidoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPedido", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion))]
    public partial class EntityPedido : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodigoPedidoField;
        
        private int EstadoField;
        
        private System.DateTime FechaEntregaField;
        
        private System.DateTime FechaPagoField;
        
        private System.DateTime FechaPedidoField;
        
        private int IDEmpresaField;
        
        private int IDEncargadoField;
        
        private SGI.Proxy.Services.PedidoServices.KeyPedido KeyField;
        
        private decimal RetencionField;
        
        private decimal TotalBrutoField;
        
        private decimal TotalNetoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPedido
        {
            get
            {
                return this.CodigoPedidoField;
            }
            set
            {
                this.CodigoPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaEntrega
        {
            get
            {
                return this.FechaEntregaField;
            }
            set
            {
                this.FechaEntregaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPedido
        {
            get
            {
                return this.FechaPedidoField;
            }
            set
            {
                this.FechaPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEmpresa
        {
            get
            {
                return this.IDEmpresaField;
            }
            set
            {
                this.IDEmpresaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDEncargado
        {
            get
            {
                return this.IDEncargadoField;
            }
            set
            {
                this.IDEncargadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.PedidoServices.KeyPedido Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Retencion
        {
            get
            {
                return this.RetencionField;
            }
            set
            {
                this.RetencionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBruto
        {
            get
            {
                return this.TotalBrutoField;
            }
            set
            {
                this.TotalBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalNeto
        {
            get
            {
                return this.TotalNetoField;
            }
            set
            {
                this.TotalNetoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPedidoPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Pagination")]
    public partial class EntityPedidoPaginacion : SGI.Proxy.Services.PedidoServices.EntityPedido
    {
        
        private SGI.Proxy.Services.PedidoServices.EntityPaginacion EntityPaginacionField;
        
        private string EstadoNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.PedidoServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoNombre
        {
            get
            {
                return this.EstadoNombreField;
            }
            set
            {
                this.EstadoNombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityDetallePedido", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityDetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CantidadField;
        
        private int EstadoField;
        
        private SGI.Proxy.Services.PedidoServices.KeyDetallePedido KeyField;
        
        private decimal RetencionField;
        
        private decimal TotalBrutoField;
        
        private decimal TotalNetoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.PedidoServices.KeyDetallePedido Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Retencion
        {
            get
            {
                return this.RetencionField;
            }
            set
            {
                this.RetencionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalBruto
        {
            get
            {
                return this.TotalBrutoField;
            }
            set
            {
                this.TotalBrutoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalNeto
        {
            get
            {
                return this.TotalNetoField;
            }
            set
            {
                this.TotalNetoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyDetallePedido", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyDetallePedido : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDPedidoField;
        
        private int IDProductoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDPedido
        {
            get
            {
                return this.IDPedidoField;
            }
            set
            {
                this.IDPedidoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProducto
        {
            get
            {
                return this.IDProductoField;
            }
            set
            {
                this.IDProductoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.PedidoServices.IPedidoServices")]
    public interface IPedidoServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/SelectByKey", ReplyAction="http://tempuri.org/IPedidoServices/SelectByKeyResponse")]
        SGI.Proxy.Services.PedidoServices.EntityPedido SelectByKey(SGI.Proxy.Services.PedidoServices.KeyPedido oKeyPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/SelectByKey", ReplyAction="http://tempuri.org/IPedidoServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> SelectByKeyAsync(SGI.Proxy.Services.PedidoServices.KeyPedido oKeyPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Select", ReplyAction="http://tempuri.org/IPedidoServices/SelectResponse")]
        SGI.Proxy.Services.PedidoServices.EntityPedido[] Select(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Select", ReplyAction="http://tempuri.org/IPedidoServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido[]> SelectAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/SelectPagging", ReplyAction="http://tempuri.org/IPedidoServices/SelectPaggingResponse")]
        SGI.Proxy.Services.PedidoServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.PedidoServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/SelectPagging", ReplyAction="http://tempuri.org/IPedidoServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.PedidoServices.SelectPaggingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Insert", ReplyAction="http://tempuri.org/IPedidoServices/InsertResponse")]
        SGI.Proxy.Services.PedidoServices.EntityPedido Insert(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Insert", ReplyAction="http://tempuri.org/IPedidoServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> InsertAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Update", ReplyAction="http://tempuri.org/IPedidoServices/UpdateResponse")]
        SGI.Proxy.Services.PedidoServices.EntityPedido Update(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Update", ReplyAction="http://tempuri.org/IPedidoServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> UpdateAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Delete", ReplyAction="http://tempuri.org/IPedidoServices/DeleteResponse")]
        SGI.Proxy.Services.PedidoServices.EntityPedido Delete(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/Delete", ReplyAction="http://tempuri.org/IPedidoServices/DeleteResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> DeleteAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/InsertPedidoCompleto", ReplyAction="http://tempuri.org/IPedidoServices/InsertPedidoCompletoResponse")]
        int InsertPedidoCompleto(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido, SGI.Proxy.Services.PedidoServices.EntityDetallePedido[] oListDetallePedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPedidoServices/InsertPedidoCompleto", ReplyAction="http://tempuri.org/IPedidoServices/InsertPedidoCompletoResponse")]
        System.Threading.Tasks.Task<int> InsertPedidoCompletoAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido, SGI.Proxy.Services.PedidoServices.EntityDetallePedido[] oListDetallePedido);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion oEntityPedidoPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion oEntityPedidoPaginacion)
        {
            this.oEntityPedidoPaginacion = oEntityPedidoPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion oEntityPedidoPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion[] SelectPaggingResult, SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion oEntityPedidoPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityPedidoPaginacion = oEntityPedidoPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidoServicesChannel : SGI.Proxy.Services.PedidoServices.IPedidoServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidoServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.PedidoServices.IPedidoServices>, SGI.Proxy.Services.PedidoServices.IPedidoServices
    {
        
        public PedidoServicesClient()
        {
        }
        
        public PedidoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PedidoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PedidoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PedidoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.PedidoServices.EntityPedido SelectByKey(SGI.Proxy.Services.PedidoServices.KeyPedido oKeyPedido)
        {
            return base.Channel.SelectByKey(oKeyPedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> SelectByKeyAsync(SGI.Proxy.Services.PedidoServices.KeyPedido oKeyPedido)
        {
            return base.Channel.SelectByKeyAsync(oKeyPedido);
        }
        
        public SGI.Proxy.Services.PedidoServices.EntityPedido[] Select(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.Select(oEntityPedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido[]> SelectAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.SelectAsync(oEntityPedido);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.PedidoServices.SelectPaggingResponse SGI.Proxy.Services.PedidoServices.IPedidoServices.SelectPagging(SGI.Proxy.Services.PedidoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion[] SelectPagging(ref SGI.Proxy.Services.PedidoServices.EntityPedidoPaginacion oEntityPedidoPaginacion)
        {
            SGI.Proxy.Services.PedidoServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.PedidoServices.SelectPaggingRequest();
            inValue.oEntityPedidoPaginacion = oEntityPedidoPaginacion;
            SGI.Proxy.Services.PedidoServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.PedidoServices.IPedidoServices)(this)).SelectPagging(inValue);
            oEntityPedidoPaginacion = retVal.oEntityPedidoPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.PedidoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
        
        public SGI.Proxy.Services.PedidoServices.EntityPedido Insert(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.Insert(oEntityPedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> InsertAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.InsertAsync(oEntityPedido);
        }
        
        public SGI.Proxy.Services.PedidoServices.EntityPedido Update(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.Update(oEntityPedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> UpdateAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.UpdateAsync(oEntityPedido);
        }
        
        public SGI.Proxy.Services.PedidoServices.EntityPedido Delete(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.Delete(oEntityPedido);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.PedidoServices.EntityPedido> DeleteAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido)
        {
            return base.Channel.DeleteAsync(oEntityPedido);
        }
        
        public int InsertPedidoCompleto(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido, SGI.Proxy.Services.PedidoServices.EntityDetallePedido[] oListDetallePedido)
        {
            return base.Channel.InsertPedidoCompleto(oEntityPedido, oListDetallePedido);
        }
        
        public System.Threading.Tasks.Task<int> InsertPedidoCompletoAsync(SGI.Proxy.Services.PedidoServices.EntityPedido oEntityPedido, SGI.Proxy.Services.PedidoServices.EntityDetallePedido[] oListDetallePedido)
        {
            return base.Channel.InsertPedidoCompletoAsync(oEntityPedido, oListDetallePedido);
        }
    }
}
