//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.ProductoServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyProducto", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyProducto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDProductoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDProducto
        {
            get
            {
                return this.IDProductoField;
            }
            set
            {
                this.IDProductoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityProducto", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion))]
    public partial class EntityProducto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
 
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CantidadMinimaInventarioField;
        
        private int CantidadinventarioField;
        
        private string DescripcionCortaField;
        
        private string DescripcionLargaField;
        
        private int EstadoField;
        
        private int IdGrupoField;
        
        private SGI.Proxy.Services.ProductoServices.KeyProducto KeyField;
        
        private string NombreField;
        
        private decimal PrecioUnitarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadMinimaInventario
        {
            get
            {
                return this.CantidadMinimaInventarioField;
            }
            set
            {
                this.CantidadMinimaInventarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidadinventario
        {
            get
            {
                return this.CantidadinventarioField;
            }
            set
            {
                this.CantidadinventarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionCorta
        {
            get
            {
                return this.DescripcionCortaField;
            }
            set
            {
                this.DescripcionCortaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionLarga
        {
            get
            {
                return this.DescripcionLargaField;
            }
            set
            {
                this.DescripcionLargaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGrupo
        {
            get
            {
                return this.IdGrupoField;
            }
            set
            {
                this.IdGrupoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.ProductoServices.KeyProducto Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityProductoPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityProductoPaginacion : SGI.Proxy.Services.ProductoServices.EntityProducto
    {
        
        private SGI.Proxy.Services.ProductoServices.EntityPaginacion EntityPaginacionField;
        
        private string EstadoNombreField;
        
        private string GrupoNombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.ProductoServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoNombre
        {
            get
            {
                return this.EstadoNombreField;
            }
            set
            {
                this.EstadoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoNombre
        {
            get
            {
                return this.GrupoNombreField;
            }
            set
            {
                this.GrupoNombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.ProductoServices.IProductoServices")]
    public interface IProductoServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/SelectByKey", ReplyAction="http://tempuri.org/IProductoServices/SelectByKeyResponse")]
        SGI.Proxy.Services.ProductoServices.EntityProducto SelectByKey(SGI.Proxy.Services.ProductoServices.KeyProducto oKeyProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/SelectByKey", ReplyAction="http://tempuri.org/IProductoServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto> SelectByKeyAsync(SGI.Proxy.Services.ProductoServices.KeyProducto oKeyProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/Select", ReplyAction="http://tempuri.org/IProductoServices/SelectResponse")]
        SGI.Proxy.Services.ProductoServices.EntityProducto[] Select();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/Select", ReplyAction="http://tempuri.org/IProductoServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto[]> SelectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/Insert", ReplyAction="http://tempuri.org/IProductoServices/InsertResponse")]
        SGI.Proxy.Services.ProductoServices.EntityProducto Insert(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/Insert", ReplyAction="http://tempuri.org/IProductoServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto> InsertAsync(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/Update", ReplyAction="http://tempuri.org/IProductoServices/UpdateResponse")]
        SGI.Proxy.Services.ProductoServices.EntityProducto Update(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/Update", ReplyAction="http://tempuri.org/IProductoServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto> UpdateAsync(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/SelectPagging", ReplyAction="http://tempuri.org/IProductoServices/SelectPaggingResponse")]
        SGI.Proxy.Services.ProductoServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.ProductoServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoServices/SelectPagging", ReplyAction="http://tempuri.org/IProductoServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.ProductoServices.SelectPaggingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion oEntityProductoPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion oEntityProductoPaginacion)
        {
            this.oEntityProductoPaginacion = oEntityProductoPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion oEntityProductoPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion[] SelectPaggingResult, SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion oEntityProductoPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityProductoPaginacion = oEntityProductoPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoServicesChannel : SGI.Proxy.Services.ProductoServices.IProductoServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.ProductoServices.IProductoServices>, SGI.Proxy.Services.ProductoServices.IProductoServices
    {
        
        public ProductoServicesClient()
        {
        }
        
        public ProductoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ProductoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ProductoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.ProductoServices.EntityProducto SelectByKey(SGI.Proxy.Services.ProductoServices.KeyProducto oKeyProducto)
        {
            return base.Channel.SelectByKey(oKeyProducto);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto> SelectByKeyAsync(SGI.Proxy.Services.ProductoServices.KeyProducto oKeyProducto)
        {
            return base.Channel.SelectByKeyAsync(oKeyProducto);
        }
        
        public SGI.Proxy.Services.ProductoServices.EntityProducto[] Select()
        {
            return base.Channel.Select();
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto[]> SelectAsync()
        {
            return base.Channel.SelectAsync();
        }
        
        public SGI.Proxy.Services.ProductoServices.EntityProducto Insert(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto)
        {
            return base.Channel.Insert(oEntityProducto);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto> InsertAsync(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto)
        {
            return base.Channel.InsertAsync(oEntityProducto);
        }
        
        public SGI.Proxy.Services.ProductoServices.EntityProducto Update(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto)
        {
            return base.Channel.Update(oEntityProducto);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.EntityProducto> UpdateAsync(SGI.Proxy.Services.ProductoServices.EntityProducto oEntityProducto)
        {
            return base.Channel.UpdateAsync(oEntityProducto);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.ProductoServices.SelectPaggingResponse SGI.Proxy.Services.ProductoServices.IProductoServices.SelectPagging(SGI.Proxy.Services.ProductoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion[] SelectPagging(ref SGI.Proxy.Services.ProductoServices.EntityProductoPaginacion oEntityProductoPaginacion)
        {
            SGI.Proxy.Services.ProductoServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.ProductoServices.SelectPaggingRequest();
            inValue.oEntityProductoPaginacion = oEntityProductoPaginacion;
            SGI.Proxy.Services.ProductoServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.ProductoServices.IProductoServices)(this)).SelectPagging(inValue);
            oEntityProductoPaginacion = retVal.oEntityProductoPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.ProductoServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.ProductoServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
    }
}
