//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.TiendaServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyTienda", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyTienda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CodTiendaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodTienda
        {
            get
            {
                return this.CodTiendaField;
            }
            set
            {
                this.CodTiendaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityTienda", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion))]
    public partial class EntityTienda : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DireccionField;
        
        private int EstadoField;
        
        private string IdDistritoField;
        
        private string IdProvinciaField;
        
        private string IdRegionField;
        
        private SGI.Proxy.Services.TiendaServices.KeyTienda KeyField;
        
        private string NombreTiendaField;
        
        private string ReferenciaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDistrito
        {
            get
            {
                return this.IdDistritoField;
            }
            set
            {
                this.IdDistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRegion
        {
            get
            {
                return this.IdRegionField;
            }
            set
            {
                this.IdRegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.TiendaServices.KeyTienda Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTienda
        {
            get
            {
                return this.NombreTiendaField;
            }
            set
            {
                this.NombreTiendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia
        {
            get
            {
                return this.ReferenciaField;
            }
            set
            {
                this.ReferenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityTiendaPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Pagination")]
    public partial class EntityTiendaPaginacion : SGI.Proxy.Services.TiendaServices.EntityTienda
    {
        
        private SGI.Proxy.Services.TiendaServices.EntityPaginacion EntityPaginacionField;
        
        private string EstadoNombreField;
        
        private string NombreDepartamentoField;
        
        private string NombreDistritoField;
        
        private string NombreProvinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.TiendaServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoNombre
        {
            get
            {
                return this.EstadoNombreField;
            }
            set
            {
                this.EstadoNombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDepartamento
        {
            get
            {
                return this.NombreDepartamentoField;
            }
            set
            {
                this.NombreDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreDistrito
        {
            get
            {
                return this.NombreDistritoField;
            }
            set
            {
                this.NombreDistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreProvincia
        {
            get
            {
                return this.NombreProvinciaField;
            }
            set
            {
                this.NombreProvinciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.TiendaServices.ITiendaServices")]
    public interface ITiendaServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/SelectByKey", ReplyAction="http://tempuri.org/ITiendaServices/SelectByKeyResponse")]
        SGI.Proxy.Services.TiendaServices.EntityTienda SelectByKey(SGI.Proxy.Services.TiendaServices.KeyTienda oKeyTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/SelectByKey", ReplyAction="http://tempuri.org/ITiendaServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> SelectByKeyAsync(SGI.Proxy.Services.TiendaServices.KeyTienda oKeyTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Select", ReplyAction="http://tempuri.org/ITiendaServices/SelectResponse")]
        SGI.Proxy.Services.TiendaServices.EntityTienda[] Select(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Select", ReplyAction="http://tempuri.org/ITiendaServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda[]> SelectAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/SelectPagging", ReplyAction="http://tempuri.org/ITiendaServices/SelectPaggingResponse")]
        SGI.Proxy.Services.TiendaServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.TiendaServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/SelectPagging", ReplyAction="http://tempuri.org/ITiendaServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.TiendaServices.SelectPaggingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Insert", ReplyAction="http://tempuri.org/ITiendaServices/InsertResponse")]
        SGI.Proxy.Services.TiendaServices.EntityTienda Insert(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Insert", ReplyAction="http://tempuri.org/ITiendaServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> InsertAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Update", ReplyAction="http://tempuri.org/ITiendaServices/UpdateResponse")]
        SGI.Proxy.Services.TiendaServices.EntityTienda Update(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Update", ReplyAction="http://tempuri.org/ITiendaServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> UpdateAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Delete", ReplyAction="http://tempuri.org/ITiendaServices/DeleteResponse")]
        SGI.Proxy.Services.TiendaServices.EntityTienda Delete(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITiendaServices/Delete", ReplyAction="http://tempuri.org/ITiendaServices/DeleteResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> DeleteAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion oEntityTiendaPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion oEntityTiendaPaginacion)
        {
            this.oEntityTiendaPaginacion = oEntityTiendaPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion oEntityTiendaPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion[] SelectPaggingResult, SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion oEntityTiendaPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityTiendaPaginacion = oEntityTiendaPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITiendaServicesChannel : SGI.Proxy.Services.TiendaServices.ITiendaServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TiendaServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.TiendaServices.ITiendaServices>, SGI.Proxy.Services.TiendaServices.ITiendaServices
    {
        
        public TiendaServicesClient()
        {
        }
        
        public TiendaServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public TiendaServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TiendaServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public TiendaServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.TiendaServices.EntityTienda SelectByKey(SGI.Proxy.Services.TiendaServices.KeyTienda oKeyTienda)
        {
            return base.Channel.SelectByKey(oKeyTienda);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> SelectByKeyAsync(SGI.Proxy.Services.TiendaServices.KeyTienda oKeyTienda)
        {
            return base.Channel.SelectByKeyAsync(oKeyTienda);
        }
        
        public SGI.Proxy.Services.TiendaServices.EntityTienda[] Select(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.Select(oEntityTienda);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda[]> SelectAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.SelectAsync(oEntityTienda);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.TiendaServices.SelectPaggingResponse SGI.Proxy.Services.TiendaServices.ITiendaServices.SelectPagging(SGI.Proxy.Services.TiendaServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion[] SelectPagging(ref SGI.Proxy.Services.TiendaServices.EntityTiendaPaginacion oEntityTiendaPaginacion)
        {
            SGI.Proxy.Services.TiendaServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.TiendaServices.SelectPaggingRequest();
            inValue.oEntityTiendaPaginacion = oEntityTiendaPaginacion;
            SGI.Proxy.Services.TiendaServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.TiendaServices.ITiendaServices)(this)).SelectPagging(inValue);
            oEntityTiendaPaginacion = retVal.oEntityTiendaPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.TiendaServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
        
        public SGI.Proxy.Services.TiendaServices.EntityTienda Insert(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.Insert(oEntityTienda);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> InsertAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.InsertAsync(oEntityTienda);
        }
        
        public SGI.Proxy.Services.TiendaServices.EntityTienda Update(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.Update(oEntityTienda);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> UpdateAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.UpdateAsync(oEntityTienda);
        }
        
        public SGI.Proxy.Services.TiendaServices.EntityTienda Delete(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.Delete(oEntityTienda);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.TiendaServices.EntityTienda> DeleteAsync(SGI.Proxy.Services.TiendaServices.EntityTienda oEntityTienda)
        {
            return base.Channel.DeleteAsync(oEntityTienda);
        }
    }
}
