//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.UbigeoServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityDistrito", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityDistrito : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EstadoField;
        
        private SGI.Proxy.Services.UbigeoServices.KeyDistrito KeyField;
        
        private string NombreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.UbigeoServices.KeyDistrito Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyDistrito", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyDistrito : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdDepartamentoField;
        
        private string IdDistritoField;
        
        private string IdProvinciaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDistrito
        {
            get
            {
                return this.IdDistritoField;
            }
            set
            {
                this.IdDistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityProvincia", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityProvincia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EstadoField;
        
        private SGI.Proxy.Services.UbigeoServices.KeyProvincia KeyField;
        
        private string NombreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.UbigeoServices.KeyProvincia Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyProvincia", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyProvincia : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdDepartamentoField;
        
        private string IdProvinciaField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityDepartamento", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityDepartamento : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int EstadoField;
        
        private SGI.Proxy.Services.UbigeoServices.KeyDepartamento KeyField;
        
        private string NombreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.UbigeoServices.KeyDepartamento Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyDepartamento", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyDepartamento : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdDepartamentoField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.UbigeoServices.IUbigeoServices")]
    public interface IUbigeoServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServices/SelectDistrito", ReplyAction="http://tempuri.org/IUbigeoServices/SelectDistritoResponse")]
        SGI.Proxy.Services.UbigeoServices.EntityDistrito[] SelectDistrito(SGI.Proxy.Services.UbigeoServices.EntityDistrito oEntityDistrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServices/SelectDistrito", ReplyAction="http://tempuri.org/IUbigeoServices/SelectDistritoResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UbigeoServices.EntityDistrito[]> SelectDistritoAsync(SGI.Proxy.Services.UbigeoServices.EntityDistrito oEntityDistrito);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServices/SelectProvincia", ReplyAction="http://tempuri.org/IUbigeoServices/SelectProvinciaResponse")]
        SGI.Proxy.Services.UbigeoServices.EntityProvincia[] SelectProvincia(SGI.Proxy.Services.UbigeoServices.EntityProvincia oEntityProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServices/SelectProvincia", ReplyAction="http://tempuri.org/IUbigeoServices/SelectProvinciaResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UbigeoServices.EntityProvincia[]> SelectProvinciaAsync(SGI.Proxy.Services.UbigeoServices.EntityProvincia oEntityProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServices/SelectDepartamento", ReplyAction="http://tempuri.org/IUbigeoServices/SelectDepartamentoResponse")]
        SGI.Proxy.Services.UbigeoServices.EntityDepartamento[] SelectDepartamento(SGI.Proxy.Services.UbigeoServices.EntityDepartamento oEntityDepartamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbigeoServices/SelectDepartamento", ReplyAction="http://tempuri.org/IUbigeoServices/SelectDepartamentoResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UbigeoServices.EntityDepartamento[]> SelectDepartamentoAsync(SGI.Proxy.Services.UbigeoServices.EntityDepartamento oEntityDepartamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUbigeoServicesChannel : SGI.Proxy.Services.UbigeoServices.IUbigeoServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UbigeoServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.UbigeoServices.IUbigeoServices>, SGI.Proxy.Services.UbigeoServices.IUbigeoServices
    {
        
        public UbigeoServicesClient()
        {
        }
        
        public UbigeoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public UbigeoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public UbigeoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public UbigeoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public SGI.Proxy.Services.UbigeoServices.EntityDistrito[] SelectDistrito(SGI.Proxy.Services.UbigeoServices.EntityDistrito oEntityDistrito)
        {
            return base.Channel.SelectDistrito(oEntityDistrito);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UbigeoServices.EntityDistrito[]> SelectDistritoAsync(SGI.Proxy.Services.UbigeoServices.EntityDistrito oEntityDistrito)
        {
            return base.Channel.SelectDistritoAsync(oEntityDistrito);
        }
        
        public SGI.Proxy.Services.UbigeoServices.EntityProvincia[] SelectProvincia(SGI.Proxy.Services.UbigeoServices.EntityProvincia oEntityProvincia)
        {
            return base.Channel.SelectProvincia(oEntityProvincia);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UbigeoServices.EntityProvincia[]> SelectProvinciaAsync(SGI.Proxy.Services.UbigeoServices.EntityProvincia oEntityProvincia)
        {
            return base.Channel.SelectProvinciaAsync(oEntityProvincia);
        }
        
        public SGI.Proxy.Services.UbigeoServices.EntityDepartamento[] SelectDepartamento(SGI.Proxy.Services.UbigeoServices.EntityDepartamento oEntityDepartamento)
        {
            return base.Channel.SelectDepartamento(oEntityDepartamento);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UbigeoServices.EntityDepartamento[]> SelectDepartamentoAsync(SGI.Proxy.Services.UbigeoServices.EntityDepartamento oEntityDepartamento)
        {
            return base.Channel.SelectDepartamentoAsync(oEntityDepartamento);
        }
    }
}
