//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGI.Proxy.Services.UsuarioServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityUsuario", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion))]
    public partial class EntityUsuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ClaveField;
        
        private int EstadoField;
        
        private SGI.Proxy.Services.UsuarioServices.KeyUsuario KeyField;
        
        private string UsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave
        {
            get
            {
                return this.ClaveField;
            }
            set
            {
                this.ClaveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.UsuarioServices.KeyUsuario Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyUsuario", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities.Keys")]
    public partial class KeyUsuario : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDUsuarioField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IDUsuario
        {
            get
            {
                return this.IDUsuarioField;
            }
            set
            {
                this.IDUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityUsuarioPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityUsuarioPaginacion : SGI.Proxy.Services.UsuarioServices.EntityUsuario
    {
        
        private SGI.Proxy.Services.UsuarioServices.EntityPaginacion EntityPaginacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SGI.Proxy.Services.UsuarioServices.EntityPaginacion EntityPaginacion
        {
            get
            {
                return this.EntityPaginacionField;
            }
            set
            {
                this.EntityPaginacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityPaginacion", Namespace="http://schemas.datacontract.org/2004/07/SGISystem.Domain.Entities")]
    public partial class EntityPaginacion : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PageIndexField;
        
        private int RowCountField;
        
        private int RowsPerPageField;
        
        private string SortDirField;
        
        private string SortTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsPerPage
        {
            get
            {
                return this.RowsPerPageField;
            }
            set
            {
                this.RowsPerPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortDir
        {
            get
            {
                return this.SortDirField;
            }
            set
            {
                this.SortDirField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortType
        {
            get
            {
                return this.SortTypeField;
            }
            set
            {
                this.SortTypeField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SGI.Proxy.Services.UsuarioServices.IUsuarioServices")]
    public interface IUsuarioServices
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Autenticar", ReplyAction="http://tempuri.org/IUsuarioServices/AutenticarResponse")]
        bool Autenticar(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Autenticar", ReplyAction="http://tempuri.org/IUsuarioServices/AutenticarResponse")]
        System.Threading.Tasks.Task<bool> AutenticarAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Insert", ReplyAction="http://tempuri.org/IUsuarioServices/InsertResponse")]
        SGI.Proxy.Services.UsuarioServices.EntityUsuario Insert(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Insert", ReplyAction="http://tempuri.org/IUsuarioServices/InsertResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> InsertAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Update", ReplyAction="http://tempuri.org/IUsuarioServices/UpdateResponse")]
        SGI.Proxy.Services.UsuarioServices.EntityUsuario Update(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Update", ReplyAction="http://tempuri.org/IUsuarioServices/UpdateResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> UpdateAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Delete", ReplyAction="http://tempuri.org/IUsuarioServices/DeleteResponse")]
        SGI.Proxy.Services.UsuarioServices.EntityUsuario Delete(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Delete", ReplyAction="http://tempuri.org/IUsuarioServices/DeleteResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> DeleteAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/SelectByKey", ReplyAction="http://tempuri.org/IUsuarioServices/SelectByKeyResponse")]
        SGI.Proxy.Services.UsuarioServices.EntityUsuario SelectByKey(SGI.Proxy.Services.UsuarioServices.KeyUsuario oKeyUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/SelectByKey", ReplyAction="http://tempuri.org/IUsuarioServices/SelectByKeyResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> SelectByKeyAsync(SGI.Proxy.Services.UsuarioServices.KeyUsuario oKeyUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Select", ReplyAction="http://tempuri.org/IUsuarioServices/SelectResponse")]
        SGI.Proxy.Services.UsuarioServices.EntityUsuario[] Select(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/Select", ReplyAction="http://tempuri.org/IUsuarioServices/SelectResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario[]> SelectAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/SelectPagging", ReplyAction="http://tempuri.org/IUsuarioServices/SelectPaggingResponse")]
        SGI.Proxy.Services.UsuarioServices.SelectPaggingResponse SelectPagging(SGI.Proxy.Services.UsuarioServices.SelectPaggingRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores de devolución.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsuarioServices/SelectPagging", ReplyAction="http://tempuri.org/IUsuarioServices/SelectPaggingResponse")]
        System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.UsuarioServices.SelectPaggingRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPagging", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion oEntityUsuarioPaginacion;
        
        public SelectPaggingRequest()
        {
        }
        
        public SelectPaggingRequest(SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion oEntityUsuarioPaginacion)
        {
            this.oEntityUsuarioPaginacion = oEntityUsuarioPaginacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectPaggingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SelectPaggingResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion[] SelectPaggingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion oEntityUsuarioPaginacion;
        
        public SelectPaggingResponse()
        {
        }
        
        public SelectPaggingResponse(SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion[] SelectPaggingResult, SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion oEntityUsuarioPaginacion)
        {
            this.SelectPaggingResult = SelectPaggingResult;
            this.oEntityUsuarioPaginacion = oEntityUsuarioPaginacion;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsuarioServicesChannel : SGI.Proxy.Services.UsuarioServices.IUsuarioServices, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsuarioServicesClient : System.ServiceModel.ClientBase<SGI.Proxy.Services.UsuarioServices.IUsuarioServices>, SGI.Proxy.Services.UsuarioServices.IUsuarioServices
    {
        
        public UsuarioServicesClient()
        {
        }
        
        public UsuarioServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public UsuarioServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public UsuarioServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public UsuarioServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool Autenticar(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.Autenticar(oEntityUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> AutenticarAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.AutenticarAsync(oEntityUsuario);
        }
        
        public SGI.Proxy.Services.UsuarioServices.EntityUsuario Insert(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.Insert(oEntityUsuario);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> InsertAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.InsertAsync(oEntityUsuario);
        }
        
        public SGI.Proxy.Services.UsuarioServices.EntityUsuario Update(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.Update(oEntityUsuario);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> UpdateAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.UpdateAsync(oEntityUsuario);
        }
        
        public SGI.Proxy.Services.UsuarioServices.EntityUsuario Delete(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.Delete(oEntityUsuario);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> DeleteAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.DeleteAsync(oEntityUsuario);
        }
        
        public SGI.Proxy.Services.UsuarioServices.EntityUsuario SelectByKey(SGI.Proxy.Services.UsuarioServices.KeyUsuario oKeyUsuario)
        {
            return base.Channel.SelectByKey(oKeyUsuario);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario> SelectByKeyAsync(SGI.Proxy.Services.UsuarioServices.KeyUsuario oKeyUsuario)
        {
            return base.Channel.SelectByKeyAsync(oKeyUsuario);
        }
        
        public SGI.Proxy.Services.UsuarioServices.EntityUsuario[] Select(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.Select(oEntityUsuario);
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.EntityUsuario[]> SelectAsync(SGI.Proxy.Services.UsuarioServices.EntityUsuario oEntityUsuario)
        {
            return base.Channel.SelectAsync(oEntityUsuario);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SGI.Proxy.Services.UsuarioServices.SelectPaggingResponse SGI.Proxy.Services.UsuarioServices.IUsuarioServices.SelectPagging(SGI.Proxy.Services.UsuarioServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPagging(request);
        }
        
        public SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion[] SelectPagging(ref SGI.Proxy.Services.UsuarioServices.EntityUsuarioPaginacion oEntityUsuarioPaginacion)
        {
            SGI.Proxy.Services.UsuarioServices.SelectPaggingRequest inValue = new SGI.Proxy.Services.UsuarioServices.SelectPaggingRequest();
            inValue.oEntityUsuarioPaginacion = oEntityUsuarioPaginacion;
            SGI.Proxy.Services.UsuarioServices.SelectPaggingResponse retVal = ((SGI.Proxy.Services.UsuarioServices.IUsuarioServices)(this)).SelectPagging(inValue);
            oEntityUsuarioPaginacion = retVal.oEntityUsuarioPaginacion;
            return retVal.SelectPaggingResult;
        }
        
        public System.Threading.Tasks.Task<SGI.Proxy.Services.UsuarioServices.SelectPaggingResponse> SelectPaggingAsync(SGI.Proxy.Services.UsuarioServices.SelectPaggingRequest request)
        {
            return base.Channel.SelectPaggingAsync(request);
        }
    }
}
